name: Java CI with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --exclude-task test
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        USERNAME: ubunttu
        HOST: ec2-52-78-18-217.ap-northeast-2.compute.amazonaws.com
        SCRIPT: whoami
        KEY: ${{ secrets.SSH_DEPLOYMENT_KEY }}
