name: '[Deploy] Super-Invention Server'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Testing SSH connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          whoami
          stat app/*.jar
          
    - name: Deploy to server
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SSH_HOST }}
        PORT: 22
        USERNAME: ${{ secrets.SSH_USER }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "./build/libs/app.jar"
        target: "./app/temp"
        strip_components: 3

    - name: Launch Script in Remote Server
      if: ${{ success() }}
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ~/app && sh deploy.sh
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USER }}
        key:  ${{ secrets.SSH_KEY }}
        args: "-tt"