name: '[Deploy] Super-Invention Server 도커배포'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: BootImageBuild And Push to DOCKER HUB
        run: ./gradlew bootBuildImage --imageName=${{secrets.APP_IMG_NAME}}
          && docker login --username ${{secrets.DOCKER_USER}} --password ${{secrets.DOCKER_USER_PASSWD}}
          && docker push ${{secrets.APP_IMG_NAME}}

      - name: Launch Script in Remote Server
        if: ${{ success() }}
        uses: fifsky/ssh-action@master
        env:
          spring_datasource_url: ${{ secrets.DEV_DATASOURCE_URL }}
          spring_datasource_username: ${{ secrets.DEV_DATASOURCE_USERNAME }}
          spring_datasource_password: ${{ secrets.DEV_DATASOURCE_PASSWORD }}
          oauth_kakao_client_id: ${{ secrets.OAUTH_KAKAO_CLIENT_ID }}
          aws_s3_accessKey: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws_s3_secretAccessKey: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          host_static_path: ${{ secrets.DEV_HOST_STATIC_PATH }}
          security_jwt_token_secret-key: ${{ secrets.DEV_JWT_TOKEN_SECRET_KEY }}
          security_jwt_token_expire-day: ${{ secrets.DEV_JWT_TOKEN_EXPIRE_DAY }}
          aws_s3_endpointUrl: ${{ secrets.DEV_AWS_S3_ENDPOINT_URL }}
        with:
          command: |
            cd ~/app-server
            export spring_datasource_url=${{ secrets.DEV_DATASOURCE_URL }}
            export spring_datasource_username=${{ secrets.DEV_DATASOURCE_USERNAME }}
            export spring_datasource_password=${{ secrets.DEV_DATASOURCE_PASSWORD }}
            export oauth_kakao_client_id=${{ secrets.OAUTH_KAKAO_CLIENT_ID }}
            export aws_s3_accessKey=${{ secrets.AWS_S3_ACCESS_KEY }}
            export aws_s3_secretAccessKey=${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
            export host_static_path=${{ secrets.DEV_HOST_STATIC_PATH }}
            export jwt_token_secret_key=${{ secrets.DEV_JWT_TOKEN_SECRET_KEY }}
            export aws_s3_endpointUrl=${{ secrets.DEV_AWS_S3_ENDPOINT_URL }}
            sh server-image-deploy.sh
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          args: "-tt"
